// Build-time BDF -> C header baker. Reads a plain-text BDF bitmap font,
// decodes every glyph's bitmap fully (no bit-packing — one byte per pixel,
// 0 or 255), and emits a header with a BitFontGlyph[96] metrics table
// (ASCII 0x20..0x7F, see include/bitfont.h) plus the concatenated pixel
// data. This keeps all font-format parsing at build time: the shipped
// runtime (source/backend/text.c) just copies precomputed bytes into a GL
// atlas, no BDF/OTB/PCF parsing in the binary at all.
//
// Usage: fonts_tool <input.bdf> <output.h> <SYMBOL_PREFIX>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_GLYPH_DIM 64
#define FIRST_CODEPOINT 0x20
#define GLYPH_COUNT 96 // 0x20..0x7F inclusive

typedef struct {
    int have;
    int width, height, bearing_x, bearing_y, advance;
    unsigned char pixels[MAX_GLYPH_DIM * MAX_GLYPH_DIM];
} Glyph;

static int hex_nibble(char c) {
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    return 0;
}

int main(int argc, char **argv) {
    if (argc != 4) {
        fprintf(stderr, "usage: %s <input.bdf> <output.h> <SYMBOL_PREFIX>\n", argv[0]);
        return 1;
    }

    FILE *in = fopen(argv[1], "r");
    if (!in) { fprintf(stderr, "fonts_tool: cannot open input %s\n", argv[1]); return 1; }

    static Glyph glyphs[GLYPH_COUNT];
    memset(glyphs, 0, sizeof(glyphs));

    int font_ascent = 0, font_descent = 0;
    int fbb_w = 0, fbb_h = 0;

    char line[512];
    int in_char = 0;
    int encoding = -1, dwidth = 0, bbw = 0, bbh = 0, bbxoff = 0, bbyoff = 0;
    int in_bitmap = 0, bitmap_row = 0;

    while (fgets(line, sizeof(line), in)) {
        // Strip trailing newline/CR so sscanf/strncmp don't trip on it.
        size_t n = strlen(line);
        while (n > 0 && (line[n - 1] == '\n' || line[n - 1] == '\r')) line[--n] = '\0';

        if (strncmp(line, "FONT_ASCENT ", 12) == 0) { sscanf(line + 12, "%d", &font_ascent); continue; }
        if (strncmp(line, "FONT_DESCENT ", 13) == 0) { sscanf(line + 13, "%d", &font_descent); continue; }
        if (strncmp(line, "FONTBOUNDINGBOX ", 16) == 0) { sscanf(line + 16, "%d %d", &fbb_w, &fbb_h); continue; }

        if (strncmp(line, "STARTCHAR", 9) == 0) {
            in_char = 1;
            encoding = -1; dwidth = 0; bbw = bbh = bbxoff = bbyoff = 0;
            in_bitmap = 0; bitmap_row = 0;
            continue;
        }
        if (!in_char) continue;

        if (strncmp(line, "ENCODING ", 9) == 0) { sscanf(line + 9, "%d", &encoding); continue; }
        if (strncmp(line, "DWIDTH ", 7) == 0) { sscanf(line + 7, "%d", &dwidth); continue; }
        if (strncmp(line, "BBX ", 4) == 0) { sscanf(line + 4, "%d %d %d %d", &bbw, &bbh, &bbxoff, &bbyoff); continue; }
        if (strcmp(line, "BITMAP") == 0) { in_bitmap = 1; bitmap_row = 0; continue; }

        if (strcmp(line, "ENDCHAR") == 0) {
            int idx = encoding - FIRST_CODEPOINT;
            if (idx >= 0 && idx < GLYPH_COUNT && bbw > 0 && bbh > 0 &&
                bbw <= MAX_GLYPH_DIM && bbh <= MAX_GLYPH_DIM) {
                Glyph *g = &glyphs[idx];
                g->have = 1;
                g->width = bbw;
                g->height = bbh;
                g->bearing_x = bbxoff;
                g->bearing_y = bbyoff + bbh; // BDF yoff = baseline->bottom row; we want baseline->top row
                g->advance = dwidth;
            }
            in_char = 0;
            in_bitmap = 0;
            continue;
        }

        if (in_bitmap && bitmap_row < bbh) {
            int idx = encoding - FIRST_CODEPOINT;
            Glyph *g = (idx >= 0 && idx < GLYPH_COUNT) ? &glyphs[idx] : NULL;
            int row_bytes = (bbw + 3) / 4; // BDF pads each row to a whole hex digit (nibble)
            for (int x = 0; x < bbw; x++) {
                int nibble_i = x / 4;
                int bit_in_nibble = 3 - (x % 4);
                if (nibble_i >= row_bytes || (size_t)nibble_i >= strlen(line)) continue;
                int nibble = hex_nibble(line[nibble_i]);
                int bit = (nibble >> bit_in_nibble) & 1;
                if (g && bbw <= MAX_GLYPH_DIM && bbh <= MAX_GLYPH_DIM) {
                    g->pixels[bitmap_row * bbw + x] = bit ? 255 : 0;
                }
            }
            bitmap_row++;
        }
    }
    fclose(in);

    if (font_ascent == 0 && font_descent == 0 && fbb_h > 0) {
        // Fallback for BDFs without FONT_ASCENT/FONT_DESCENT properties.
        font_ascent = fbb_h - 2;
        font_descent = -2;
    }

    FILE *out = fopen(argv[2], "wb");
    if (!out) { fprintf(stderr, "fonts_tool: cannot open output %s\n", argv[2]); return 1; }

    const char *prefix = argv[3];
    fprintf(out, "// Generated by tools/fonts.c from %s — do not edit.\n", argv[1]);
    fprintf(out, "#pragma once\n");
    fprintf(out, "#include \"bitfont.h\"\n\n");

    fprintf(out, "static const unsigned char %s_PIXELS[] = {\n", prefix);
    int offsets[GLYPH_COUNT];
    int running_offset = 0;
    int col = 0;
    for (int i = 0; i < GLYPH_COUNT; i++) {
        offsets[i] = running_offset;
        Glyph *g = &glyphs[i];
        int count = g->width * g->height;
        for (int p = 0; p < count; p++) {
            fprintf(out, "%u,", g->pixels[p]);
            if (++col == 20) { fputc('\n', out); col = 0; }
        }
        running_offset += count;
    }
    if (running_offset == 0) fprintf(out, "0"); // avoid a zero-size array
    fprintf(out, "\n};\n\n");

    fprintf(out, "static const BitFontGlyph %s_GLYPHS[%d] = {\n", prefix, GLYPH_COUNT);
    for (int i = 0; i < GLYPH_COUNT; i++) {
        Glyph *g = &glyphs[i];
        fprintf(out, "    {%d,%d,%d,%d,%d,%d}, // codepoint 0x%02x\n",
                g->width, g->height, g->bearing_x, g->bearing_y, g->advance, offsets[i],
                FIRST_CODEPOINT + i);
    }
    fprintf(out, "};\n\n");

    fprintf(out, "static const int %s_ASCENT = %d;\n", prefix, font_ascent);
    fprintf(out, "static const int %s_DESCENT = %d;\n", prefix, -font_descent);
    fprintf(out, "static const int %s_CELL_W = %d;\n", prefix, fbb_w);
    fprintf(out, "static const int %s_CELL_H = %d;\n", prefix, font_ascent + font_descent);

    fclose(out);
    return 0;
}
