// Generic "xxd -i" replacement: embeds an arbitrary file as a C byte array.
// Used by CMakeLists.txt at build time for the bundled font and shaders, so
// the core stays one self-contained .so with nothing to locate at runtime.
//
// Usage: xxd_tool <input-file> <output-header> <symbol-name>
#include <stdio.h>

int main(int argc, char **argv) {
    if (argc != 4) {
        fprintf(stderr, "usage: %s <input-file> <output-header> <symbol-name>\n", argv[0]);
        return 1;
    }

    FILE *in = fopen(argv[1], "rb");
    if (!in) {
        fprintf(stderr, "xxd_tool: cannot open input %s\n", argv[1]);
        return 1;
    }
    FILE *out = fopen(argv[2], "wb");
    if (!out) {
        fprintf(stderr, "xxd_tool: cannot open output %s\n", argv[2]);
        fclose(in);
        return 1;
    }

    fprintf(out, "// Generated by tools/xxd.c from %s — do not edit.\n", argv[1]);
    fprintf(out, "#pragma once\n");
    fprintf(out, "static const unsigned char %s[] = {\n", argv[3]);

    unsigned char buf[4096];
    size_t total = 0;
    size_t n;
    int col = 0;
    while ((n = fread(buf, 1, sizeof(buf), in)) > 0) {
        for (size_t i = 0; i < n; i++) {
            fprintf(out, "0x%02x,", buf[i]);
            total++;
            if (++col == 12) {
                fputc('\n', out);
                col = 0;
            }
        }
    }
    fprintf(out, "\n};\n");
    fprintf(out, "static const unsigned int %s_len = %zuu;\n", argv[3], total);

    fclose(in);
    fclose(out);
    return 0;
}
